# Generated by Django 4.2 on 2026-05-11 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120, verbose_name='Модель')),
                ('car_class', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('suv', 'SUV')], max_length=20, verbose_name='Класс')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('transmission', models.CharField(choices=[('automatic', 'Автомат'), ('manual', 'Механика')], max_length=20, verbose_name='Коробка')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Мест')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/час')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'ordering': ['car_class', '-price_per_hour', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало аренды')),
                ('end_at', models.DateTimeField(verbose_name='Окончание аренды')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='created', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cars.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
