# Generated by Django 4.2 on 2026-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='cars/', verbose_name='Фото (загрузка)'),
        ),
    ]
