# Generated by Django 4.2 on 2026-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий менеджера'),
        ),
    ]
