# Generated by Django 4.2 on 2026-05-13 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_bookingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('canceled', 'Отменено')], max_length=20, verbose_name='Статус до')),
                ('to_status', models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('canceled', 'Отменено')], max_length=20, verbose_name='Статус после')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cars.booking', verbose_name='Бронирование')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
